[[entry]]
played_at = "2026-05-16T02:25:38Z"
path = "spotify:track:4Y8q64VnhD0vFYy9g2WFpi"
title = "It Feels So Good"
artist = "Sonique"
album = "Hear My Cry"
year = 2000
track_number = 1
duration_secs = 240

[[entry]]
played_at = "2026-05-16T02:13:46Z"
path = "spotify:track:3S6U7DuGvhorShWDHcKcBS"
title = "A State Of Mind"
artist = "Mark Foggo"
album = "Speeding My Life Away/A State Of Mind"
year = 1999
track_number = 10
duration_secs = 232

[[entry]]
played_at = "2026-05-16T02:09:48Z"
path = "spotify:track:1WCvIVgW28xxPQysW4LRPK"
title = "Miss Understanding"
artist = "Mark Foggo"
album = "Speeding My Life Away/A State Of Mind"
year = 1999
track_number = 12
duration_secs = 174

[[entry]]
played_at = "2026-05-16T02:06:39Z"
path = "spotify:track:4rBkeAUFZJcSHWr42e9CnN"
title = "Moonshine"
artist = "Jaqee, TEKA"
album = "Moonshine"
year = 2010
track_number = 1
duration_secs = 200
